version: '3.8'

services:

  db:
    image: mysql:8.0
    container_name: app_mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    volumes:
      - /home/wisam/app_volumes/db_data:/var/lib/mysql

    networks:
      - backend-net

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


  backend:
    image: cbankyemen/cby:backend
    container_name: app_backend
    restart: always

    ports:
      - "8000:80"

    environment:
      APP_NAME: "CBY Imports Platform"
      APP_ENV: production
      APP_KEY: base64:rDYeH7r2RANVkDCakt6II1xiT90PY6avnuTc7OO0HQg=
      APP_DEBUG: false
      APP_URL: /webserve
      APP_TIMEZONE: Asia/Aden
      APP_LOCALE: ar
      LOG_CHANNEL: stack
      LOGSESSION_DRIVER: database
      QUEUE_CONNECTION: sync
      CACHE_STORE: file
      SANCTUM_STATEFUL_DOMAINS: test-ifcas.ultimate-dev2.com
      SESSION_DOMAIN: 
      CORS_ALLOWED_ORIGINS: *
      OTP_TTL_SECONDS: 300
      FILE_ENCRYPTION_KEY: Dcwp4CvruTfclBuJ5xgkL6Q7+YTpfnMwUsrWN8y2mW4=
      RUN_MIGRATIONS: false
      SEED_DEMO_DATA: false
      MAIL_MAILER: smtp
      MAIL_HOST: mail.ultimate-dev2.com
      MAIL_PORT: 465
      MAIL_USERNAME: ifcas-docker@ultimate-dev2.com
      MAIL_PASSWORD: d~TzEkc%&L.*
      MAIL_ENCRYPTION: ssl
      MAIL_FROM_ADDRESS: ifcas-docker@ultimate-dev2.com
      MAIL_FROM_NAME: "${APP_NAME}"
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_DATABASE}
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

    depends_on:
      db:
        condition: service_healthy

    volumes:
      - /home/wisam/app_volumes/backend_docs:/home/wisam/app_volumes/backend_docs

    networks:
      - backend-net
      - frontend-net


  frontend:
    image: cbankyemen/cby:frontend
    container_name: app_frontend
    restart: always

    ports:
      - "8001:80"

    depends_on:
      - backend

    networks:
      - frontend-net


networks:

  backend-net:
    driver: bridge

  frontend-net:
    driver: bridge
